### ISSUE TITLE
Testing device with IOS ibeacon broadcast

### ISSUE THREAD

**Issue by afshawnlotfi** [neXenio/BLE-Indoor-Positioning#155]
Hi,
I really like this project and got it setup on my nexus 7. I am using my iphone to broadcast an iBeacon using this test project ([https://github.com/Darktt/iBeacon-Demo](https://github.com/Darktt/iBeacon-Demo)), and I set the UUID to "03253fdd-55cb-44c2-a1eb-80c8355f8291" and "acfd065e-c3c0-11e3-9bbe-1a514932ac01" but the demo app doesn't recognize either one. Could someone please help me get started here. Really want to contribute because this project is amazing!

**Comment by Steppschuh** [comment]
Hey,
glad you're interested in this project. Unfortunately there's currently no real getting started guide available, you can track the progress in #89.

The UUID `03253fdd-55cb-44c2-a1eb-80c8355f8291` is correct, it should at least show up in the chart view. The other views may be empty because there's no matching `LocationProvider` for your major & minor combination (refer to #144). 

I would suggest using the [nRF Connect](https://github.com/NordicSemiconductor/Android-nRF-Connect) app to check if your iPhone is actually advertising valid iBeacon frames.
