### ISSUE TITLE
Using MacAddress instead of minor to get location

### ISSUE THREAD

**Issue by hadiidbouk** [neXenio/BLE-Indoor-Positioning#80]
Hello,

There is a TODO to get the location from advertising packets, can you explain how you guys can make that happen if iBeacon broadcasts only one advertising packet which has a unique ID number comprising of three parts - UUID, Major, and Minor.

The sample shows that every beacon get the location depending on the minor, but the value of the minor can be changed from any smartphone.

Isn't better to use the Mac Address instead of the minor for now ? Like a HashMap.

```java
public class IBeaconLocationProvider<B extends IBeacon> extends BeaconLocationProvider<B> {

    public IBeaconLocationProvider(B beacon) {
        super(beacon);
    }

    @Override
    public void updateLocation() {
        //AdvertisingPacket advertisingPacket = beacon.getLatestAdvertisingPacket();
        //location = new Location();
        // TODO: get location from advertising packets
    }
}
```

**Comment by Steppschuh** [comment]
You could encode geo coordinates (or distance and angle to a reference location) into the UUID or the 4 bytes major and minor. You could also look up the geo coordinates from an API that you provide, or a local data store. Because you have a reference to the beacon, you could also use its mac address for these lookups.

All this is up to you, that's why we provided the generic `LocationProvider` interface and the abstract `BeaconLocationProvider` class that you can implement or extend.

This is related to #10.

**Comment by hadiidbouk** [comment]
Thank you
